#这是一个手动创建一个endpoints，通常用作一个服务并非部署在k8s集群内部，但我们又需要使用到这个服务。所以需要自定一个Endpoints服务。
apiVersion: v1
kind: Endpoints
metadata:
  name: mysql-external
  namespace: default
subsets:
#添加mysql外部地址
- addresses:
  - ip: 172.29.9.51
  - ip: 172.29.9.52
  ports:
  - name: mysql
    port: 3306
    protocol: TCP
   #手动指定非就绪的IP地址。
  notReadyAddresses: 172.29.9.53
---
#同时创建一个同名同命名空间service，这样会自动与Endpoints所绑定。
apiVersion: v1
kind: Service
metadata:
  name: mysql-external
  namespace: default
spec:
  type: ClusterIP
  ports:
  - name: mysql
    port: 3306
    targetPort: 3306
    protocol: TCP
