apiVersion: v1
kind: Pod
metadata:
  name: secrets-env-demo
  namespace: default
spec:
  containers:
  - name: mariadb
    image: mariadb
    imagePullPolicy: IfNotPresent
    env:
    #指定环境变量并像这个环境变量传值，这里的意思是往 MYSQL_ROOT_PASSWOR 环境变量传值， MYSQL_ROOT_PASSWOR 这个环境变量是容器内部有的，所有要往环境变量中传值的时候需要容器内有这个变量名。
    - name: MYSQL_ROOT_PASSWORD
      valueFrom:    # 键值引用；
        secretKeyRef:       #引用的Secret对象的名称，需要与该Pod位于同已名称空间，而且是之前已经提前创建好的,如果没有提前创建的话，会报错的。
          name: mysql-root-authn      #指定键名
          key: password               #指定键值
#通过环境变量传值的话，只限于第一次容器初始化的时候有效，之后改动的话是无效的。