groups:
- name: AllInstances
  rules:
  - alert: InstanceDown
  # Condition for alerting
  expr: up == 0
  for: 1m
  annotations:
   title: 'Instance down'
   description: Instance has been down for more than 1 minute.
  labels: 
    severity: 'critical'
