apiVersion: v1
kind: Pod
metadata:
  name: volumes-pvc-demo
  namespace: default
spec:
  containers:
  - name: redis
    image: redis:alpine
    imagePullPolicy: IfNotPresent
    #一定要配置用户ID，不然会没权限，启动失败
    securityContext:
      runAsUser: 1099
    ports:
    - containerPort: 6379
      name: redisport
    volumeMounts:
    - mountPath: /data
      name: redis-rbd-vol
  volumes:
  - name: redis-rbd-vol
      #指定要绑定的已创建的pvc名
    persistentVolumeClaim:
      claimName: pvc-demo-0001
