apiVersion: v1
kind: Service
metadata:
  name: ng-deploy-80 
  namespace: linux39
spec:
  ports:
  - name: http
    port: 80
    targetPort: 80
    protocol: TCP
  type: ClusterIP
  selector:
    app: ng-deploy-80
